### ISSUE TITLE
Run hanging

### ISSUE THREAD

**Issue by emptyr1** [joshiadvait8/nse-data#1]
Hey great work here :) 
Does the program run finish for you? For some reason the program hangs at:
```
Base_url = "https://www.nseindia.com/live_market/dynaContent/live_watch/option_chain/optionKeys.jsp?symbol=" + symbol + "&date=" + expdate
page = requests.get(Base_url) <-- hangs here doesn't return
```

**Comment by sisco0** [comment]
Added the PR for fixing this issue, as it seems that the server was blocking the requests without complete headers information.
This was tackled before at https://github.com/joshiadvait8/nse-data/blob/a992252c42bc4ab04820945e48127d0d8baf8bb7/NSE_option_chain_to%20excel.py#L14 but not at this script.

**Comment by joshiadvait8** [comment]
Do give it a 🌟 if you like it
Thanks for adding headers
